GOCDB/gocdb

- htdocs/web_portal/static_html/goc5_logo.html
- htdocs/web_portal/views/downtime/downtimes_calendar.php
Fixed the incorrect date formatting, and changed the first day of the week to Monday in the datetimepicker.
(also updated the version number to 5.6rc1)
> Downtime calendar date fixes

- lib/Gocdb_Services/PI/GetService.php
Additionally added comments to paging code
> Adding paging info to XML returned from GetService PI

- htdocs/PI/index.php
- lib/Gocdb_Services/PI/GetDowntime.php
Not ready for merging. I need to have a play with the doctrine paginator bits first.
> [WIP] Added IPIQueryPageable interface to GetDowntime class

- INSTALL.md
- tests/README.md
install.md is updated to reflect improvements in the composer install process for windows and to make it extra clear as to where some commands need to be run
the read me for the tests is updated to reflect the use of composer and git has helpfully removed some trailing white space
> Docs - install.md & tests readme

- INSTALL.md
*some minor formatting changes
*removal of erroneous trailing double space that was causing a line break
*Addition of some more detail tot eh section on deploying an existing dumpfile
> Install.md - more content

- lib/Gocdb_Services/ServiceService.php
- lib/Gocdb_Services/Site.php
Corrections to a few comments associated with code for custom properties
in the site and service services. Removal of a couple of obsolete
commented out lines of code. Changes to comments only.
> Tidy up custom properties comments

- INSTALL.md
Reflects need to recompile compiled entites
> Update to docs for schema change

- config/gocdb_schema.xml
- htdocs/web_portal/controllers/utils.php
- htdocs/web_portal/views/service/add_service_endpoint.php
- htdocs/web_portal/views/service/edit_service_endpoint.php
- htdocs/web_portal/views/service/view_service_endpoint.php
- lib/Doctrine/entities/EndpointLocation.php
- lib/Gocdb_Services/PI/GetDowntime.php
- lib/Gocdb_Services/PI/GetDowntimeFallback.php
- lib/Gocdb_Services/PI/GetDowntimeOffsetPaging.php
- lib/Gocdb_Services/PI/GetDowntimesToBroadcast.php
- lib/Gocdb_Services/PI/GetService.php
- lib/Gocdb_Services/PI/GetServiceGroup.php
- lib/Gocdb_Services/PI/GetServiceOffsetPaging.php
- lib/Gocdb_Services/ServiceGroup.php
- lib/Gocdb_Services/ServiceService.php
CONTAINS SCHEMA CHANGES.
This commit adds an email field and a monitored boolean to the service end point entity.  The web portal is updated to reflect this and the PI output is updated to include the monitored value where relevant. The email value is displayed on the one PI query which is level 2 protected. For the rest the code is in place to be implemented if required.
> Addition of email and monitored fields to service endpoints

- config/gocdb_schema.xml
- config/gocdbssl.conf
- htdocs/web_portal/controllers/service/add_endpoint_properties.php
- htdocs/web_portal/controllers/service/add_service_properties.php
- htdocs/web_portal/controllers/service_group/add_service_group_properties.php
- htdocs/web_portal/controllers/site/add_site_properties.php
- htdocs/web_portal/controllers/utils.php
- lib/Gocdb_Services/ServiceGroup.php
- lib/Gocdb_Services/ServiceService.php
- lib/Gocdb_Services/Site.php
* Move code for trimming keys and values of extension properties from controller to model layer
* Update the schema to improve docs and reflect new thinking on extension property whitespace
* Apache 2.2 appears to require the "RewriteEngine on" line within the
directory definition. Without it, the rewrite rules in the directory
definition are ignored.
> Updates to write-api

- lib/Gocdb_Services/ServiceService.php
Adds user authorisation checks on users adding and editing endpoints in
the service service. Previously this had been only done within the page
controllers.
> Add authrosiation checks to endpoint functions

- .travis.yml
- .travis/mysql_bootstrap_doctrine.php
- .travis/mysql_bootstrap_pdo.php
- .travis/setup
- tests/doctrine/ExtensionsTest.php
- tests/doctrine/resources/sampleFixtureData1.php
> Travis using MySQL

- htdocs/web_portal/controllers/service/edit_service_endpoint.php
- lib/Gocdb_Services/ServiceService.php
Removes dependency of the function on the service ID
> Refactor edit serviceEndpoint function

- lib/Gocdb_Services/NGI.php
> correct typo in text of exception in NGI service

- changeLog.txt
- htdocs/web_portal/static_html/goc5_logo.html
* Increment version in web portal to 5.7.2
* Update change log to reflect switch to using GitHub to track changes.
* removal of white space
> Increment version and depreciate change log

- .travis.yml
- .travis/run_tests.sh
- htdocs/PI/index.php
- htdocs/web_portal/controllers/admin/delete_ngi.php
- htdocs/web_portal/controllers/project/delete_project.php
- lib/Doctrine/entities/EndpointProperty.php
- lib/Gocdb_Services/PI/GetCertStatusChanges.php
- lib/Gocdb_Services/PI/GetCertStatusDate.php
- lib/Gocdb_Services/PI/GetNGI.php
- lib/Gocdb_Services/PI/GetNGIContacts.php
- lib/Gocdb_Services/PI/GetNGIList.php
- lib/Gocdb_Services/PI/GetProjectContacts.php
- lib/Gocdb_Services/PI/GetServiceGroupRole.php
- lib/Gocdb_Services/PI/GetServiceTypes.php
- lib/Gocdb_Services/PI/GetSiteContacts.php
- lib/Gocdb_Services/PI/GetSiteCountPerCountry.php
- lib/Gocdb_Services/PI/GetSiteSecurityInfo.php
- lib/Gocdb_Services/PI/GetSubGridList.php
- lib/Gocdb_Services/PI/GetUser.php
- lib/Gocdb_Services/PI/IPIQuery.php
- lib/Gocdb_Services/PI/IPIQueryPageable.php
- lib/Gocdb_Services/PI/IPIQueryRenderable.php
- lib/Gocdb_Services/PI/QueryBuilders/Helpers.php
- tests/doctrine/bootstrap_pdo_TEMPLATE.php
The test suite doesn't cover everything, so this seems like a low-effort way to get some extra coverage for free.
> travis: Use built-in PHP syntax checker on modified PHP files

- htdocs/web_portal/views/search_results.php
Change that had been made locally on production server.
> Minor change to search results page

- INSTALL.md
Include misc. changes to improve installation documentation.
> Updates to installation doc

- htdocs/landing/home.css
- htdocs/web_portal/css/web_portal.css
Merge in after #120 and rebase so that this PR only changes white space.
> Replaced all tabs with 4 spaces in the CSS for both the landing page and portal.

- htdocs/web_portal/views/fragments/addPropertiesConfirmation.php
- htdocs/web_portal/views/fragments/propertiesTable.php
- htdocs/web_portal/views/fragments/viewPropertiesTable.php
- htdocs/web_portal/views/fragments/viewRoleActionsTable.php
- htdocs/web_portal/views/ngi/view_ngi.php
- htdocs/web_portal/views/ngi/view_ngis.php
- htdocs/web_portal/views/political_role/view_role_action_mappings.php
- htdocs/web_portal/views/project/view_all.php
- htdocs/web_portal/views/project/view_project.php
- htdocs/web_portal/views/scope_help.php
- htdocs/web_portal/views/search_results.php
- htdocs/web_portal/views/service/se_downtimes.php
- htdocs/web_portal/views/service/view_all.php
- htdocs/web_portal/views/service/view_service.php
- htdocs/web_portal/views/service_group/view_all.php
- htdocs/web_portal/views/service_group/view_sgroup_downtimes.php
- htdocs/web_portal/views/site/site_downtimes.php
- htdocs/web_portal/views/site/view_all.php
- htdocs/web_portal/views/site/view_site.php
* Ensure all tables that have a head have a body
* Remove stubs of old odd-even row highlighting code
* Remove redundant size checks around iterators (they will not iterate anyway)
* Use a consistent control block syntax (no endif please)
* Correct helper comments at end of long loops
* Remove commented out code blocks
* Sort out some of the indentation insanity
> Rationalise table generation

- htdocs/landing/aup.html
- htdocs/landing/privacy.html
> Change return-to-homepage url to root dir

- htdocs/web_portal/css/web_portal.css
9pt **is** a bit on the small side, view it [here](https://host-172-16-113-91.nubes.stfc.ac.uk/portal/).
> Increase body font size of web portal to 10pt

- htdocs/web_portal/static_html/goc5_logo.html
in preparation for a merge of `dev` to `master` and deployment on gocdb-test
> Increment version number to 5.7.3

- htdocs/web_portal/static_html/goc5_logo.html
this is running on https://gocdb-test.esc.rl.ac.uk/portal/
> Release 5.7.4 to dev

- htdocs/PI/write/PIWriteRequest.php
Fixes a couple of comment typos and removes a bug in the write API
> Fix typos in comments and a small bug in Write API

- htdocs/web_portal/css/web_portal.css
- htdocs/web_portal/views/downtime/downtimes_overview.php
- htdocs/web_portal/views/site/site_downtimes.php
- htdocs/web_portal/views/site/view_site.php
Fixes issue #169: More consistent wording for display at site and detailed downtime levels. Minor tweeks to include icon graphics and remove word-wrapping.
> Changed wording plus some UI tweeking.

- htdocs/PI/write/PIWriteRequest.php
General refactor of the code behind the Write API to break up large functions and generally improve readability.
Depends on: ~#179, #177~
> Refactor write API

- htdocs/PI/write/PIWriteRequest.php
- lib/Gocdb_Services/Site.php
~depends on #180~
* Slight refactor of write API to reduce repeated code in relation to
authorisation
* improve error messages and response codes
* Fix minor error in text of error message in write API
> Refactor write api authorisation (+minor)

- htdocs/PI/write/PIWriteRequest.php
Refactor the getRequestContent function:
* sort out indentation
* simplify some of the logic
> Refactor Write API request processing

- htdocs/PI/write/PIWriteRequest.php
- lib/Gocdb_Services/ServiceService.php
- lib/Gocdb_Services/Site.php
> Function naming

- .travis.yml
- .travis/run_tests.sh
Logging into [Codedov](https://codecov.io) with GitHub should show you the details.
I've disabled commenting by Codecov, but it should start showing PR statuses eventually (it might need it to be active on the dev branch first).
> Add coverage tests and uploading to Codecov

- htdocs/web_portal/css/web_portal.css
- htdocs/web_portal/views/ngi/view_ngi.php
- htdocs/web_portal/views/project/view_project.php
- htdocs/web_portal/views/service_group/view_sgroup.php
- htdocs/web_portal/views/site/view_site.php
- htdocs/web_portal/views/user/view_user.php
Add a CSS class for the 'person' icon and use this for styling each time the icon is used.
> Use CSS class for person icon

- htdocs/PI/write/PIWriteRequest.php
- htdocs/web_portal/static_html/goc5_logo.html
- lib/Authentication/AuthTokens/ShibAuthToken.php
this is running on https://gocdb-www-2.gridpp.rl.ac.uk/portal/
> Release 5.7.5 to dev

- htdocs/PI/write/PIWriteRequest.php
- lib/Gocdb_Services/AbstractEntityService.php
- lib/Gocdb_Services/ServiceService.php
- lib/Gocdb_Services/Site.php
- tests/DoctrineTestSuite1.php
- tests/doctrine/TestUtil.php
- tests/writeAPI/abstractClass.php
- tests/writeAPI/endpointMethods.php
- tests/writeAPI/extensionPropertyAbstract.php
- tests/writeAPI/serviceMethods.php
- tests/writeAPI/siteMethods.php
Depends on ~#157, #161, #177, #179, #180, #187, #189, #193, #196, #208, #220~ 
Adds remaining write API functionality and functional tests for all write API methods.
See also: https://wiki.egi.eu/wiki/GOCDB/Write_API/Technical_Documentation#Supported_methods_in_GOCDB_5.8 (documentation will be merged following release)
> Final pull request for 5.8 Write API extensions

- htdocs/web_portal/views/service_group/add_ses.php
- htdocs/web_portal/views/service_group/add_ses_body.php
> Changes references to "SE" on the Add_Service_Group_SEs page to "service"

- htdocs/web_portal/views/fragments/viewPropertiesTable.php
> Make urls in the extension properties table clickable

- config/gocdb_schema.xml
- htdocs/web_portal/GOCDB_monitor/tests.php
- htdocs/web_portal/views/fragments/addPropertiesView.php
- tests/DoctrineTestSuite1.php
- tests/doctrine/TestUtil.php
- tests/unit/lib/Gocdb_Services/ServiceServiceTest.php
Including basic ServiceService extension property input validation tests. Fixes #214
> Allow <> through service extension property validation.

- config/gocdb_schema.xml
- htdocs/web_portal/controllers/user/utils.php
- htdocs/web_portal/css/web_portal.php
- htdocs/web_portal/views/user/edit_user.php
- lib/Doctrine/entities/User.php
- lib/Gocdb_Services/User.php
> Initial changes allowing unlinking to Home Site

- htdocs/web_portal/static_html/goc5_logo.html
It's running here: https://gocdb-preprod.egi.eu/
> Release 5.8.0 to dev

- htdocs/web_portal/views/site/added_api_auth.php
> Api credential pull request

- htdocs/web_portal/static_html/goc5_logo.html
It's running here: https://host-172-16-113-65.nubes.stfc.ac.uk
> Release 5.8.1 to dev

- htdocs/web_portal/components/Get_User_Principle.php
- htdocs/web_portal/static_html/goc5_logo.html
It's running here: https://host-172-16-101-131.nubes.stfc.ac.uk/portal
> Release 5.9.0 to dev

- htdocs/web_portal/GOCDB_monitor/check.php
> Take monitoring error info URL from local_info.xml

- .github/actions/run_tests.sh
Prerequisite for #357 tests to pass.
> Use phpunit configuration from tests directory

- composer.json
- composer.lock
All tests pass and web interface and PI appear functional, but without extensive checking. Includes a commit of the composer lock file generated before any ORM changes.
> ORM 2.4 to 2.5

- .codeclimate.yml
Only partially addresses #270 .
> Add Code Climate config file for PHP checks

- config/RoleActionMappings.xml
- htdocs/web_portal/controllers/ngi/view_ngi.php
- htdocs/web_portal/controllers/ngi/view_ngis.php
- htdocs/web_portal/views/fragments/hidePersonalData.php
- htdocs/web_portal/views/fragments/requestRole.php
- htdocs/web_portal/views/ngi/view_ngi.php
- htdocs/web_portal/views/ngi/view_ngis.php
- htdocs/web_portal/views/project/view_project.php
- htdocs/web_portal/views/site/view_site.php
- lib/Gocdb_Services/User.php
Addresses the 3 primary (bulleted) issues in #366.
> Privacy followup

- htdocs/web_portal/views/user/link_identity.php
Resolves #371.
This nested list was missing list tags on the outer list which was making it appear wonky. Inner scope indented.
> Add unordered lists tags to fix wonky list

- config/gocdb_schema.xml
Whislt working on #396 and #397, I noticed this file used a mix of spaces and tabs. It was also indented inconsistently.
This PR fixes both.
> Replace tabs for spaces and reindent gocdb_schema.xml

- config/local_info.xml
- htdocs/web_portal/components/Draw_Components/draw_page_components.php
- htdocs/web_portal/css/web_portal.php
- lib/Gocdb_Services/Config.php
> Option for page banner on all pages

- htdocs/web_portal/components/Draw_Components/draw_page_components.php
- htdocs/web_portal/css/web_portal.php
- lib/Gocdb_Services/Config.php
Applies coding standards to files changed by #403
> Page banner standards

- composer.json
- composer.lock
Depends on #334 
Use current PHP Mess Detector, compatible with improved option control for customised GOCDB ruleset.
> Add phpmd to composer

- INSTALL.md
Add changes for using Oracle XE 18c instead of 11g.
> Update Oracle import instructions.

- htdocs/web_portal/views/user/edit_user.php
- htdocs/web_portal/views/user/register.php
Resolves #303 
Update "unaccentuated" to "unaccented" in
htdocs/web_portal/views/user/edit_user.php
htdocs/web_portal/views/user/register.php
> Unaccentuate "unaccentuated"

- htdocs/web_portal/views/scope.php
> Change link for viewing services within scope.

- lib/Doctrine/deploy/AddNGIs.php
- added space after if and foreach statements to pass code checks
as asked to do in #394
> Fixes codestyle issue in AddNGIs

- htdocs/web_portal/controllers/user/view_user.php
- htdocs/web_portal/views/user/view_user.php
- lib/Gocdb_Services/Role.php
- tests/unit/lib/Gocdb_Services/RoleServiceTest2.php
In combination with additions to #369 fixes #366 (final 3 bullets -  https://github.com/GOCDB/gocdb/issues/366#issue-1293298800)
> Include NGI role in revocation evaluation for orphaned API credentials

- htdocs/web_portal/controllers/user/view_user.php
- htdocs/web_portal/views/user/view_user.php
- lib/Gocdb_Services/Role.php
- lib/Gocdb_Services/User.php
- tests/unit/lib/Gocdb_Services/RoleServiceTest2.php
Depends on #369 and #370 
Standards updates prompted by privacy-followup and ngi-api-creds branch commits. No functional changes.
> Code standards updates.

- htdocs/web_portal/css/web_portal.php
- htdocs/web_portal/views/admin/view_service_type.php
- htdocs/web_portal/views/downtime/view_downtime.php
- htdocs/web_portal/views/ngi/view_ngi.php
- htdocs/web_portal/views/project/view_project.php
- htdocs/web_portal/views/scope.php
- htdocs/web_portal/views/service/view_service.php
- htdocs/web_portal/views/service/view_service_endpoint.php
- htdocs/web_portal/views/service_group/view_sgroup.php
- htdocs/web_portal/views/site/view_site.php
- htdocs/web_portal/views/user/view_user.php
Closes #165 
Adds new CSS classes for the edit and delete icons and makes existing icons use this class.
> CSS class for edit and delete icons

- htdocs/web_portal/GOCDB_monitor/check.php
- htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php
- htdocs/web_portal/GOCDB_monitor/tests.php
> GT-95 Include failing test and error string in monitoring message

- htdocs/web_portal/views/user/link_identity.php
- Slim down identifier linking/recovery page to focus on important content.
- Reword some sections to hopefully be more clear.
- Add newline at end of file.
- Change some `<span>` to `<div>`.
Resolves #376
> Improve clarity of text and layout

- .github/workflows/continuous-integration.yml
- htdocs/web_portal/static_html/goc5_logo.html
Subject to #507 being merged, this PR contains no unreviewed code.
> Release 5.11.1 to master

- htdocs/web_portal/static_html/goc5_logo.html
A small release containing only PHP 7.4 / Rocky 8 related changes.
> Release 5.12.0 to dev

- .github/workflows/continuous-integration.yml
- composer-5.4.json
- composer-5.4.lock
- composer.json
- composer.lock
- htdocs/web_portal/static_html/goc5_logo.html
Subject to https://github.com/GOCDB/gocdb/pull/514 being merged, this PR contains no unreviewed code.
> Release 5.12.0 to master
