htdocs/web_portal/controllers/utils.php
The parser wasn't trimming the whitespace, causing it to try and interpret the blank line as a kvp.
=> fixed bug where blank lines caused import failure in .properties upload

INSTALL.md
The INSTALL.MD file displays fine on github, but github is more
permissive than most readers. The conent is not changed by this commit,
but I have done the following:
*Removed BASH/SQL tags from codeblocks that also include comand outputs
*Inserted empty lines before and after codeblocks
*Where blocks of code appear within bullet points, I have indented them
to ensure they appear within the bullet
*Inserted a space between headings and the initial hashes
*inserted an empty line after headings
=> Update to install md file to improve syntax

.gitignore
One more file to ignore, comes from installing composer on windows machines using the .exe file they provide
=> Update gitignore to ignore the composer set up file

lib/Doctrine/bootstrap_doctrine_TEMPLATE.php, tests/doctrine/bootstrap_doctrine_TEMPLATE.php
Charset configuration added to example oracle connection in the
bootstrap templates.
Atom has also helpfully tidied up some whitespace and CR issues
=> Update to the bootstrap template

tests/doctrine/bootstrap_pdo_TEMPLATE.php
- Add some clarity to the oracle template
- remove the include that breaks the tests if it is left in
Also Atom has helpfully cleaned up some white space
=> updates to bootstrap_pdo template

lib/Gocdb_Services/ServiceService.php
Remove the unused function 'checkNotReserved()' from the service service. It currently confuses the logic of the existing code and can be reimplemented easily enough if reserved custom properties are required
in the future. It is also not present in the site service, which is inconsistent.
=> Remove unused function from Service Service.

htdocs/web_portal/controllers/service/delete_endpoint_properties.php, lib/Gocdb_Services/ServiceService.php, lib/Gocdb_Services/Site.php, tests/doctrine/ExtensionsTest.php
- Refactors the extension properties functions in the site ans service services in order to allow for future development of the write API. In particular it abstracts out the logic of making changes to extension properties from the permissions this will allow non-user entities to make changes (e.g. Robot DNs).
- Commented out code which was echoing extension properties as part of the unit test
- Expansion and correction of a couple of comments in the Extension Properties unit test
- The code for deleting service endpoint extension properties now more closely matches that used elsewhere for deleting extension properties. This includes a change the the variables for the delete endpoint properties function, so the unit tests and web portal have been updated
to reflect this (the portal …
=> Refactor services for extension props

config/gocdb_schema.xml, htdocs/web_portal/controllers/service/add_service_endpoint.php, htdocs/web_portal/views/service/added_service_endpoint.php, htdocs/web_portal/views/service/view_service_endpoint.php, lib/Gocdb_Services/ServiceService.php
* Fixes bug that meant endpoint descriptions weren't saved when creating new endpoints
* Added endpoint description tot he table of properties on the show endpoint page
* Reorders some code for add and edit endpoint so they do things in a consistent order
* Updates the 'description' property in the gocdb xml schema for endpoints. Allows for empty strings and limits characters to 255. This reflects the in page validation that was already in place for adding and editing endpoints.
* After a new endpoint is added a a link to the new SE as well as the parent service is now displayed.
=> Tidying and bug fixes for endpointlocation

lib/Gocdb_Services/ServiceGroup.php
Ensures that that users calling the function that edits Service group
custom proeprties are actually allowed to do this.
=> Change to SG edit properties function

htdocs/web_portal/controllers/service/add_endpoint_properties.php, htdocs/web_portal/controllers/service/add_service_properties.php, htdocs/web_portal/controllers/service_group/add_service_group_properties.php, htdocs/web_portal/controllers/site/add_site_properties.php, htdocs/web_portal/views/fragments/addPropertiesConfirmation.php, lib/Doctrine/entities/EndpointProperty.php, lib/Doctrine/entities/ServiceGroupProperty.php, lib/Doctrine/entities/ServiceProperty.php, lib/Doctrine/entities/SiteProperty.php, lib/Gocdb_Services/ServiceGroup.php, lib/Gocdb_Services/ServiceService.php, lib/Gocdb_Services/Site.php
* Add constraints to the schema so that keys of custom Properties are unique to each entity.
* Re-factors the code for sites, service and endpoints to abstract out the transactional logic
* Updates the front-end to reflect this as well as changing the edit functions so that the values of existing keys can, optionally, be overwritten.
=> Add a constraint on custom properties

htdocs/PI/write/class.php
A pair of include statements in the write API class break due to case
sensitivity. This was not noticed soone because the development
envireoment did not have case sensitive file paths.
=> Fix bugs from case sensitivity in write API

config/local_info.xml
Marks the FedCloud as reserved in the local_info.xml config file.
=> Make the FedCloud scope reserved

.travis.yml, .travis/setup, .travis/sqlite_bootstrap_doctrine.php, .travis/sqlite_bootstrap_pdo.php
Add a self-contained bootstrap configuration and setup script under `.travis/` that can be run in a CI environment
Currently runs tests using PHP 5.3 against a sqlite database backend, but this can be extended to a larger build matrix in `.travis.yml` by:
* Adding more versions of PHP to the `php` list.
* Adding more DB entries to the `env` list with matching bootstrap configs.
=> Provide a configuration for travis to run unit tests

lib/Doctrine/entities/NGI.php, tests/doctrine/DoctrineCleanInsert1Test.php, tests/doctrine/ServiceMoveTest.php, tests/doctrine/SiteMoveTest.php, tests/doctrine/resources/sampleFixtureData2.php
As MySQL tables are files on disk, MySQL follows the  case-sensitivity of the Operating System,
so tests using mangled capitalisation fail.
These may have been missed before as Oracle and MySQL on Windows are case-insensitive.
This corrects the capitalisation to match that generated by Doctrine.
=> Correct capitalisation of table names in unit tests

.travis.yml
- Add Precise MySQL builds to Travis config which should enable PHP 5.3 tests to work.
- Allow Trusty PHP 5.3 build to fail as this combination is no longer supported.
=> Add Precise MySQL Travis builds

htdocs/web_portal/views/site/view_site.php
Without the empty tbody the tablesorter plugin will crash and break sorting on all tables on the page.
Don't think about it too hard, too too hard.
It's a mobius strip...
=> Always produce a table body even when empty

config/gocdb_schema.xml
Resolves #110 
Copied existing regexp for user certificate dn (which is commented out but includes bracket characters) to be used for the host dn.
=> Fix host dn regexp

htdocs/web_portal/index.php
- Change: "Denined" to "Denied"
=> Fix typo in user 'not authenticated' error message

htdocs/web_portal/views/downtime/add_downtime.php
Otherwise the first site selected or UTC is used, despite what the page may imply.
Fixes #100 :tada: :balloon: :fireworks:
=> Recalculate timezone offsets if site is changed

lib/Authentication/MyConfig1.php
- it is enabled by uncommenting this line on the production instance
anyway and this change should be merged into the main codebase
to make deployment easier.
=> Enable ShibAuthToken authentication by default

INSTALL.md, lib/Doctrine/bootstrap_doctrine_TEMPLATE.php
- Instructions for setting up a local mariaDB instance in a testing environment
- Moved some of the bootstrap template about to show that one of the commands is required in all circumstances - previous layout suggested it was only needed for Oracle based installations.
=> Update to installation Docs to include MariaDB and rejig of bootstrap template

.travis/run_tests.sh
Otherwise tests will fail, which will make us sad.
=> Exclude deleted files from PHP lint checks

htdocs/web_portal/GOCDB_monitor/tests.php
Resolves #153 
- Change `CURLOPT_SSL_VERIFYHOST` from `'1'` to `2` as `'1'` breaks on SL7 and as per what seems like [totally legit documentation](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html).
- Change `CURLOPT_SSL_VERIFYPEER` from `'0'` to `0` as per what seems like [totally legit documentation](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html). Hopefully this avoids similar future<sup>TM</sup> problems.
- Change `CURLOPT_RETURNTRANSFER` from `'1'` to `true`. This seems like it might be a php specific option and https://www.php.net/manual/en/book.curl.php says to set it to `true` not `'1'`. Hopefully this avoids similar future<sup>TM</sup> problems.
I've tested this change on gocdb-test and it doesn't break anything, so huzzah!
=> Fix monitoring checks on SL7 and hopefully future proof

lib/Gocdb_Services/ServiceService.php
As per https://ggus.eu/index.php?mode=ticket_info&ticket_id=139924
- Change the message on "production =/> monitored". Rather than list an potentially ever growing list of ServiceTypes, just say that the 'production => monitored' rule applies to the ServiceType in question. When we move to having this rule as a property of the ServiceType, we probably wouldn't want to enumerate the exceptions anyway.
- Replace three `if` statements with an `in_array` call. Atleast for now, once this is a property of the service type this may change again. This seems cleaner than a potentially ever growing number of `if` statements.
- Move 'production => monitored' rule into function
I'll open an issue stating that the 'production => monitored' rule should be a property of the ServiceType in the database …
=>  Allow "org.squid-cache.Squid" to be production and not monitored and improve handling of these cases

htdocs/PI/write/PIWriteRequest.php
If GOCDB is in read only mode and the request is not a GET request (which
isn't currently supported) then the API will return a 503 code and an
appropriate error message.
=> Add a read-only check to write API

config/gocdb_schema.xml, htdocs/web_portal/controllers/utils.php, lib/Gocdb_Services/ServiceService.php
* For legacy reasons the URLS of services have been treated as a seperate
entity for the purposes of validation. This no longer makes sense, so I
have updated the codebase to reflect that url is just another property
of a service.
=> Refactor to make service URLs less exceptional and minor other things

config/gocdb_schema.xml, htdocs/web_portal/controllers/utils.php, lib/Gocdb_Services/ServiceService.php, lib/Gocdb_Services/Validate.php
Depends on https://github.com/GOCDB/gocdb/pull/157 
* adds entries in the GOCDB schema for boolean fields of services and endpoints
* Introduces the ability to validate boolean and string properties of
entities defined in the GOCDB schema. This change is designed to not
interfere with existing behaviour of the validation tool. 
* Boolean fields in the schema are marked as such.
* Make use of new validation for SEs in web portal
=> Validate types of entity fields

htdocs/web_portal/controllers/utils.php
Came across this old downtime form function while working on the whitespace trimming. Have checked that it's not called anywhere so am removing it to improve maintainability.
=> Remove unused old downtime form function

lib/Authentication/AuthTokens/ShibAuthToken.php
I have added the uncommented out code from the local commit on gocdb-test.
Currently running [here](https://gocdb-www-preprod.gridpp.rl.ac.uk/portal/).
=> Add support for EGI Dev IdP out of the box

lib/Authentication/AuthTokens/ShibAuthToken.php
As urn:mace:egi.eu:aai.egi.eu:gocdb is being replaced in favour of an AARC-G027 [compliant one](https://aarc-project.eu/guidelines/aarc-g027/).
Running [here](https://gocdb-www-preprod.gridpp.rl.ac.uk/portal/).
=> Use new EGI Check-in entitlement to access GOCDB

config/gocdb_schema.xml
Adds a new entry to the GOCDB schema under service for a boolean "notify" field.
This should have been included in #161
=> Add service notify field to schema (missed in #161)

lib/Gocdb_Services/ServiceService.php
Enabling work for future API development
* Replace commonly repeated pattern to evaluate strings from the web portal into booleans with a dedicated function
* Change the validateProductionMonitoredCombination fucntion within the
service service so that it is more generic - allowing future use by API.
=> Service service slight refactor

htdocs/web_portal/controllers/utils.php
Resolves #82.
- Trim all free text entry form fields so that extraneous whitespace
doesn't make it either to the validation stage for some fields (leading
to an unhelpful error message) or into the database (leading to problems
with some services that use data from GOCDB).
=> Trim all free text entry form fields

.travis.yml
- Move from Ubuntu Precise to Trusty as base build, keeping Precise for
PHP 5.3 build.
- Simplify to one sqlite build as it fails.
- Add later versions of PHP to test against, adding currently failing
ones to allowed failures.
- Specify OS explicitly.
Example build here: https://travis-ci.org/tofu-rocketry/gocdb/builds/645386379
=> Update Travis build file

htdocs/PI/write/PIWriteRequest.php
Whilst PHP is not case sensitive when it comes to functions, it would be
better that we respect case, so this corrects an error that crept in
in #180.
=> Improve write API code readability by correcting error in #180

tests/DoctrineTestSuite1.php, tests/doctrine/DoctrineCleanInsert1Test.php, tests/doctrine/DowntimeServiceEndpointTest1.php, tests/doctrine/ExtensionsTest.php, tests/doctrine/NGIServiceTest.php, tests/doctrine/RoleCascadeDeletionsTest.php, tests/doctrine/RoleServiceTest.php, tests/doctrine/RolesTest.php, tests/doctrine/Scoped_IPIQuery_Test1.php, tests/doctrine/ServiceDAOTest.php, tests/doctrine/ServiceMoveTest.php, tests/doctrine/resources/sampleFixtureData1.php, tests/doctrine/resources/sampleFixtureData2.php, tests/doctrine/resources/sampleFixtureData3.php, tests/doctrine/resources/sampleFixtureData4.php, tests/doctrine/resources/sampleFixtureData5.php, tests/unit/lib/Gocdb_Services/RoleActionAuthorisationServiceTest.php, tests/unit/lib/Gocdb_Services/RoleActionMappingServiceTest.php, tests/unit/lib/Gocdb_Services/ScopeServiceTest.php, tests/unit/resources/sampleFixtureData5.php, tests/unit/resources/sampleFixtureData6.php
Generally tidy up the test suite a bit:
* Removes a quantity of commented out redundant code from across the test
suite
* Ensure uniform indenting across code within the test suite
* Tidy up some comments
* Change the way some functions are spread across lines
* Remove some empty lines
* Add some curly braces to some if statements (the code works without them, but this improves readability)
* Fix a typo in a comment in one of the unit tests
=> Tidy testing framework code

htdocs/PI/write/PIWriteRequest.php, tests/doctrine/bootstrap.php
* Rename a function in write API for clarity
* Update to comment in write API for clarity
* Deletion of commented out code from test suites
=> Minor updates

htdocs/web_portal/css/web_portal.css
Resolves #166.
This PR increases the size of new window icons from 0.75em to 1em to make them clearer which addresses my original issue with the new icon.
Example from a user page before:
And after:
=> Increase size of new window icons

htdocs/PI/write/PIWriteRequest.php, htdocs/PI/write/index.php, htdocs/PI/write/utils.php
Move obtaining authentication details out of the write API class in order to
enable future functional testing of that class
Also a minor addition of some documentation to a function
=> Refactor the write API authentication

htdocs/landing/home.css, htdocs/landing/index.html, htdocs/web_portal/components/Draw_Components/draw_page_components.php, htdocs/web_portal/css/web_portal.css
Aligns the top of the UKRI logo with the top of the other sponsor logos on the landing and in the left menu, allowing the STFC council symbol to project above the upper line, to better balance the visual weight of the logos. Is stable with IE11 so long as compatibility mode is not enabled. Also increases the size of the logos on the landing page slightly to avoid tiny-font syndrome. Some cleaning of the CSS classes and associated code. Added "part of UK Research and Innovation" to landing page acknowledgement.
Before -
After -
=> Align body of STFC logo and clean css for sponsor logos.

lib/Gocdb_Services/Site.php
* Remove blocks of commented out code from the site service
* change formating of one function description to match the rest of
GOCDB
=> Remove commented code from site service +minor

.gitignore
When testing on a active web-serving instance, this prevents .htaccess showing up as untracked in git.
=> Add base directory .htaccess to .gitignore

config/gocdb_schema.xml
Fixes #147, depends on ~#146~.
Update the x email regexs to reflect the HTML5 spec[1]. As this is xml,
ampersands need escaping as special characters.
[1] https://html.spec.whatwg.org/#e-mail-state-(type=email)
=> Update the regular expressions for emails in validation

htdocs/web_portal/views/ngi/view_ngi.php, htdocs/web_portal/views/search_results.php, htdocs/web_portal/views/service/view_service.php, htdocs/web_portal/views/service_group/view_sgroup.php, htdocs/web_portal/views/site/view_site.php
Resolves #248.
This PR corrects the spelling and also improves the messages, wherever they occur in the codebase, to clarify that registration is required and not just "auth" as you need a grid cert to get that far anyway.
Also makes the PHP logic around one of the instances consistent with the others in the same file.
=> Unregistered user protected messages fix

config/gocdb_schema.xml, htdocs/web_portal/views/user/edit_user.php, htdocs/web_portal/views/user/register.php
Fixes #176. On user edit and registration pages:
* Add title 'Mx'
* Add option for empty title
* Update Gocdb schema to allow empty string titles (simpler to
maintain than having a null option on the drop down)
* Reorder titles to be in alphabetical order
I have tested the edit page. I have not been able to test the registration page (though the code is very similar). It should be tested before merging.
=> Update to titles for users

htdocs/web_portal/static_html/read_only_warning.html
Resolves #65 (which isn't quite 4 years old yet).
This corrects the placement of the message so it appears below the GOCDB + version line and also changes it to all caps to make it more obvious.
Only tested by making edits through Firefox Web Dev tools Inspector, though it only touches HTML so should be safe, but actual testing would be a good idea.
=> Add styling to read only message

lib/Gocdb_Services/Role.php
Resolves #125
`roleId` is currently generated using the default identifier generation strategy, which differs between Oracle (`SEQUENCE` ) and MariaDB (`IDENTITY`). This value is required to create a RoleActionRecord, but under the `IDENTITY` strategy, the value is not created until insertion. In general:
> Generated entity identifiers / primary keys are guaranteed to be available after the next successful flush operation that involves the entity in question. You can not rely on a generated identifier to be available directly after invoking persist.
Adding an additional flush provides a cross platform way to ensure `roleId` exists when needed.
=> Fix adding roles on MariaDB

lib/Gocdb_Services/Site.php
Resolves #257
Currently longitude and latitude are not required and can be left blank, but with MariaDB (and possibly other updated databases) this leads to an exception when adding/editing sites:
> An exception occurred while executing 'UPDATE Sites SET latitude = ?, longitude = ?, alarmEmail = ? WHERE id = ?' with params ["", "", "", 13]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect double value: '' for column \`gocdb\`.\`Sites\`.\`latitude\` at row 1
Unentered latitude and/or longitude when adding/editing a site are replaced with `null` to solve this.
=> Fix adding/editing a Site on MariaDB

htdocs/web_portal/GOCDB_monitor/check.php, htdocs/web_portal/GOCDB_monitor/index.php, htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php, htdocs/web_portal/GOCDB_monitor/tests.php, htdocs/web_portal/controllers/site/view_all.php, lib/Gocdb_Services/Config.php, lib/Gocdb_Services/NGI.php
Resolves #263 
Enable monitoring pages to use url-based configuration plus minor logic fixes.
=> URL-based configuration monitoring fixes

htdocs/web_portal/controllers/political_role/request_role.php, lib/Gocdb_Services/EmailService.php, lib/Gocdb_Services/Factory.php, lib/Gocdb_Services/NotificationService.php
Depends on #238 
Fixes #64, fixes #163 and fixes #168.
=> Fix email issues

lib/Gocdb_Services/Downtime.php
Resolves #269
Added a check when attempting to delete a scheduled downtime to prevent deletion if the start time is within 24 hours.
As this check is also carried out for the old and new start times when editing a downtime, this functionality has been factored out into `validateStartTime`.
The additional validation when deleting a downtime has been factored out with the existing check (if the downtime is on-going) for clarity.
=> Prevent downtimes scheduled within 24 hours from being deleted

resources/QueryPopulateSSO_UsernameRunner.php
QueryPopulateSSO_UsernameRunner.php has not been working for some time, as the EGI URL (`$url`) has changed, and the proxy does not seem to work. This results in `$username1` not being populated or updated when the script is run.
`$url` has therefore been updated and the proxy settings have been removed. This appears to fix the script, correctly populating `$username1`.
=> Fix QueryPopulateSSO_UsernameRunner

htdocs/web_portal/GOCDB_monitor/check.php, htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php
Fixes #317 
Standardise on using the portal url in the monitoring checks.
=> Monitoring checks to use the same url

phpcs.xml
Only partially addresses #270, but it will be good to add this basic `phpcs.xml` and see how it goes with Codacy picking it up, then we can decide it we want to add a config for Codeclimate (and/or add Actions).
=> Add basic PHP CodeSniffer rule set

resources/RemoveInactiveUsersRunner.php
Users who have a lastLoginDate from more than 18 months ago will be removed.
Also catch the case where users who have not logged in since the addition of lastLoginDate, which means they don't have a lastLoginDate. They are also removed.
~Depends on~ #171 is now merged into dev
~Merge after #284~
=> Remove inactive users

tests/doctrine/DoctrineCleanInsert1Test.php, tests/doctrine/DowntimeServiceEndpointTest1.php, tests/doctrine/ExtensionsTest.php, tests/doctrine/NGIServiceTest.php, tests/doctrine/RoleCascadeDeletionsTest.php, tests/doctrine/RoleServiceTest.php, tests/doctrine/RolesTest.php, tests/doctrine/Scoped_IPIQuery_Test1.php, tests/doctrine/ServiceDAOTest.php, tests/doctrine/ServiceMoveTest.php, tests/doctrine/SiteMoveTest.php, tests/doctrine/Site_CertStatusLogCascadeDeletionsTest.php, tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php, tests/unit/lib/Gocdb_Services/RoleActionAuthorisationServiceTest.php, tests/unit/lib/Gocdb_Services/RoleServiceTest2.php, tests/unit/lib/Gocdb_Services/ScopeServiceTest.php, tests/unit/lib/Gocdb_Services/ServiceServiceTest.php, tests/unit/lib/Gocdb_Services/SiteServiceTest.php, tests/unit/lib/Gocdb_Services/UserServiceTest.php, tests/writeAPI/abstractClass.php
Add tearDown function to tests to properly close the
connection to the database with failure due to >150
connections default max value for MariaDB.
Auto-reformat code.
=> Prevent database connection pile-up during tests

htdocs/PI/index.php, lib/Gocdb_Services/APIAuthenticationService.php, tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php
We want the API to allow access based on OIDC Identifiers in the future., so need to generalise getAPIAuthentication.
~Still a work in progress, I should rename the `authByCert` method at least and fix the tests.~
I also wonder wether we should remove [this check](https://github.com/GOCDB/gocdb/blob/5c302472a6a7459dd4f6cd275a4f3c41f6113726/htdocs/PI/index.php#L386), maybe API access should be a function of the API Identifiers alone - not something a user can browse by virtue of their roles?
=> Refactor API Auth to support non X.509 identifiers

htdocs/PI/index.php
~~Depends on #368~~
So some methods can be accessed with just a valid identifier. 
i.e. `get_cert_status_date`, for GOCDB 5.9 it's accessible with just a valid identifier and it doesn't contain personal/contact so it should remain accessible with just a valid identifier.
=> Re-add authByAnyCert/Identifier method

config/gocdb_schema.xml, config/local_info.xml, htdocs/web_portal/controllers/admin/edit_scope.php, htdocs/web_portal/controllers/scope.php, htdocs/web_portal/controllers/utils.php, htdocs/web_portal/css/web_portal.php, htdocs/web_portal/views/admin/add_scope.php, htdocs/web_portal/views/admin/edit_scope.php, htdocs/web_portal/views/admin/edited_scope.php, htdocs/web_portal/views/scope.php, htdocs/web_portal/views/scopes.php, lib/Doctrine/deploy/AddScopes.php, lib/Doctrine/deploy/sampleData/Scopes.xml, lib/Doctrine/entities/Scope.php, lib/Gocdb_Services/Config.php, lib/Gocdb_Services/Scope.php, tests/unit/lib/Gocdb_Services/ScopeServiceTest.php
Closes #99.
Moves reserved scopes definition out of the local config xml and into the scopes table in the database as a 'reserved' boolean associated with each scope entry. Addition of consequent changes to the interface to allow those with admin privileges to set/unset the reserved state flag on a scope at creation and if editting.
Would prefer not to use '!important' in web_portal.css which serves to left-align the 'reserved' checkbox correctly under the text entry boxes for name and description in the add/edit scope dialogues.
=> Modified scope handling.

htdocs/web_portal/static_html/goc5_logo.html, resources/RemoveInactiveUsersRunner.php
Whilst testing the release, I noticed the user deletion script didn't properly handle the case where users don't have the new identifier mechanism in place (and most, if not all, of the inactive users fall into this category). Hence 0346f652fd829b97a4d06738d2b2c4dd20ec7cf0.
=> Release 5.10.0 to dev

resources/RemoveInactiveUsersRunner.php
Resolves #381 
The output:
```[root@host-172-16-113-110 resources]# php RemoveInactiveUsersRunner.php --warning_threshold 4 --deletion_threshold 8 --dry_run
Dry run is on.
Scanning user login dates in database at: Mon, 10 Oct 2022 16:08:51
User ID: 1
Months elapsed since last login: 12.78
This user will be deleted when it isn't a dry run.
User ID: 2
Months elapsed since last login: 1.81
Doing nothing.
User ID: 4
Months elapsed since last login: 5.98
Sending user warning email.
User ID: 5
Months elapsed since last login: 10.35
This user will be deleted when it isn't a dry run.
User ID: 6
Months elapsed since last login: 0.1
Doing nothing.
View the contents of InactiveUsersToBeDeleted.txt to see the list of users who would have been deleted had this not have been a dry run.
Completed ok: …
```
=> 381 user removal dry run

htdocs/PI/index.php, htdocs/web_portal/static_html/goc5_logo.html, lib/Gocdb_Services/Config.php, lib/Gocdb_Services/PI/AccessTest.php
In preparation for restricting access to personal data, this new method enables Service Owners to be able to verify their hosts will retain access to the API after access to personal data is restricted.
Required a change to `authByIdentifier` and `isRestrictPDByRole` to force the restrictions for the test method regardless of the wider API access rules. I haven't included Users in this API check as I don't want to encourage human users talking to the API.
Subject to a positive review here, I'll bump the version number up (probably to 5.10.2) and merge this in. This PR deliberately merges into master so that it can be released in isolation.
It's running in preproduction: https://gocdb-preprod.egi.eu
=> Add an access_test method to API to master

htdocs/web_portal/static_html/Help_And_Contact.html
- as old egi wiki links are out of date, references are reworked to point to somewhere appropriate
- rewording of text and reformatting of links
First part of #405
=> Remove references to EGI wiki on Help and Contact page

config/local_info.xml, lib/Gocdb_Services/Config.php, lib/Gocdb_Services/LinkIdentity.php, lib/Gocdb_Services/NotificationService.php, resources/RemoveInactiveUsersRunner.php
- removed instances where gocdb-admins@mailman.egi.eu was hardwired into code
- replaced the email addresses with a config call
- split email adresses into 'to' and 'from' addresses
- added lines in config file for to and from email adresses
- added reply-to adresses in email text when emails are sent
resolves #410
=> Add config calls so email addresses aren't hardwired into code

htdocs/PI/index.php, htdocs/web_portal/static_html/goc5_logo.html, lib/Gocdb_Services/APIAuthenticationService.php, tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php
Allow the same identifier to be used for APIauthentication entities at multiple sites
=> Same API identifier at multiple sites to master.

htdocs/PI/index.php, lib/Gocdb_Services/APIAuthenticationService.php, tests/DoctrineTestSuite1.php, tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php
Code standards to changes handling multiple API auth credentials with same identifier.
Formatting and other changes where practical and limited to files committed.
=> Code standards for multiple API auth credentials with same identifier

lib/Doctrine/deploy/AddServiceGroups.php
=> 373 deploying the sample data fails

htdocs/web_portal/views/political_role/view_requests.php
- link pointed to a deprecated documentation page
- now points to new egi documentation
=> Fix out of date link in manage roles page

lib/Gocdb_Services/APIAuthenticationService.php, lib/Gocdb_Services/Site.php
The identifier of an API credential is assumed to be unique irrespective of the type, so the type need not be
included in the uniqueness check. This also allows transition from legacy type string "X509" to "X.509" without
throwing an error when a credential user is reassigned.
=> Remove type from uniqueness check

htdocs/landing/index.php
GOCDB doesn't currently support IRIS IAM "out of the box", so the button doesn't work anyway.
=> Remove "IRIS IAM" login button from landing page

lib/Gocdb_Services/Config.php
- there was a typo in Config.php when calling GetLocalInfoXML()
- this fixes it
Resolves #434
=> Fix incorrect function call in config

lib/Gocdb_Services/Validate.php
Fixes #254
Including commit with cosmetic changes to calm PHP Mess detector warnings.
=> GT-95 Reduce xml schema file loading for validating data entry values

htdocs/PI/index.php, resources/ManageAPICredentials/ManageAPICredentials.php, resources/ManageAPICredentials/ManageAPICredentialsActions.php, resources/ManageAPICredentials/ManageAPICredentialsOptions.php, tests/DoctrineTestSuite1.php, tests/resourcesTests/ManageAPICredentialsTest.php, tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php, tests/unit/lib/Gocdb_Services/ServiceTestUtil.php, tests/unit/lib/Gocdb_Services/SiteServiceTest.php
Script and accompanying tests to filter API credentials by last-use time to allow sending warning emails and deletion of unused credentials.
Old PR: https://github.com/GOCDB/gocdb/pull/409
=> GT-91 Manage API credentials

.codeclimate.yml
Needed to enforce PSR12, see: https://docs.codeclimate.com/docs/phpcodesniffer#standard
=> Use the beta channel phpcodesniffer

config/gocdb_schema.xml, htdocs/PI/write/PIWriteRequest.php, htdocs/web_portal/controllers/admin/add_service_type.php, htdocs/web_portal/controllers/admin/edit_service_type.php, htdocs/web_portal/controllers/admin/view_service_type.php, htdocs/web_portal/controllers/utils.php, htdocs/web_portal/views/admin/add_service_type.php, htdocs/web_portal/views/admin/added_service_type.php, htdocs/web_portal/views/admin/edit_service_type.php, htdocs/web_portal/views/admin/edited_service_type.php, htdocs/web_portal/views/admin/view_service_type.php, htdocs/web_portal/views/admin/view_service_types.php, htdocs/web_portal/views/fragments/serviceTypeInfo.php, lib/Doctrine/entities/ServiceType.php, lib/Gocdb_Services/ServiceService.php, lib/Gocdb_Services/ServiceType.php, tests/DoctrineTestSuite1.php, tests/doctrine/ServiceTypeTest.php, tests/doctrine/TestUtil.php, tests/unit/lib/Gocdb_Services/ServiceServiceTest.php, tests/unit/lib/Gocdb_Services/ServiceTypeServiceTest.php, tests/writeAPI/abstractClass.php
Draft pull request while doctrine schema update issues are checked and resolved.
Add monitoring-exception-allowed flag to service type table.
Associated GUI changes and cleanups. 
Add instance count column to service type overview table. 
Add related unit tests.
Closes #156
=> GT-95 Softcoding of service type production<=>monitored service flag relations.

resources/ManageAPICredentials/ManageAPICredentialsActions.php, resources/ManageAPICredentials/ManageUnusedAPICredentials.php, resources/ManageAPICredentials/ManageUnusedAPICredentialsOptions.php, tests/DoctrineTestSuite1.php, tests/resourcesTests/ManageAPICredentialsTestUtils.php, tests/resourcesTests/ManageUnrenewedAPICredentialsTest.php, tests/resourcesTests/ManageUnusedAPICredentialsTest.php
Refactor existing last-use-time code and add prototype test as for #438
=> [GT-95] Prepare for API credential management based on renewal time

htdocs/web_portal/controllers/search.php, htdocs/web_portal/views/search_results.php, lib/Gocdb_Services/Search.php
It's often quite useful to be able to identify a site associated with an API credential, and at the moment I have to log into the database to do so, which is less than ideal.
Perhaps the "Search" functionality in portal could return the owning Site?
"Resolves #452 "
=> [GT-180] Add API credentials support to search functionality

htdocs/web_portal/views/downtime/edit_downtime.php
Fix for [GT-187].
Adding the code to its previous state. So that the changes to the code will remain to the PR itself.
[GT-187]: https://stfc.atlassian.net/browse/GT-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GT-187] Re-add line of code removed erroneously in GOCDB#471

htdocs/web_portal/controllers/user/view_user.php, htdocs/web_portal/views/user/view_user.php
[Functionality]
To help with user support when someone queries one of the account deletion emails, it would be useful to be able to see when the account was last logged in to in the web interface.
"Resolves https://github.com/GOCDB/gocdb/issues/456 ".
=> [GT-181] Add last logged in field for admins

htdocs/web_portal/controllers/service_group/add_service_group.php
If a user is an `Admin` -> they are allowed to ADD new service group's.
If a user is NOT an `Admin`:
1) Case1: User is NOT allowed to add new SG's. If a User have no roles assigned.
2) Case2: User is allowed to add new SG's. If a user is registered and have at least one role assigned with 'STATUS_GRANTED'.
Resolves #364
=> [GT-182] Add restrictions on who can create SG's

lib/Doctrine/deploy/AddSites.php
- change to use the timezone provided in the site xml, instead of UTC by default
resolves #469
=> [GT-201] Give sample data sites their correct timezone, instead of UTC by default

config/web_portal/menu.xml, config/web_portal/menu.xsd, htdocs/web_portal/controllers/service_type/view_service_type.php, htdocs/web_portal/controllers/service_type/view_service_types.php, htdocs/web_portal/controllers/utils.php, htdocs/web_portal/index.php, htdocs/web_portal/views/admin/added_service_type.php, htdocs/web_portal/views/admin/delete_service_type_denied.php, htdocs/web_portal/views/admin/edited_service_type.php, htdocs/web_portal/views/service_type/view_service_type.php, htdocs/web_portal/views/service_type/view_service_types.php
- Admin => Can do CRUD operations in `Service Types` page.
- non-Admin => Can ONLY read the data(view) in `Service Types` page.
"Resolves #126 " 
Note:
Sometimes GIT interface will not show the EOL. If the file is NOT having EOL GIT may shows `no_newline_at_end` explicitly.
=> [GT-183] Add service types page for non-admins

.github/workflows/continuous-integration.yml
- they haven't worked in a long time and we never cared, so let's not waste time and CPU cycles running the test.
=> Remove SQLite unit tests

.github/workflows/continuous-integration.yml, composer-7.4.json, composer-7.4.lock, config/gocdb_schema.xml, htdocs/web_portal/controllers/user/register.php, htdocs/web_portal/views/political_role/view_requests.php, htdocs/web_portal/views/user/view_user.php, tests/doctrine/DoctrineCleanInsert1Test.php
This PR reworks the test MariaDB tests to:
- Drop experimental PHP 7.2 and 7.3 MariaDB tests
- they have never worked and our PHP upgrade to 7 is going to be to 7.4 as this is the highest 7.X version readily install-able on Rocky8
- Drop PHP 8.0 MariaDB test for now
- it requires a later reelase of version 2.X of the Doctrine ORM before the tests will even run.
- Fix the PHP 7.4 test for MariaDB
- This involves supplying seperate composer.json/lock files to run different versions of Doctrine, as there is no version that supports both PHP <7.4 and >7.4.
- Drop the experimental from the PHP 7.4 test as it is now expected to pass.
Fixing the PHP 7.4 test for MariaDB highlighted a few things that wouldn't work under PHP 7.4 and this PR also addresses those.
- [Fix count() error in …
=> Fix PHP 7.4 MariaDB test, Drop experimental MariaDB tests

htdocs/web_portal/views/service_group/view_sgroup.php
Update CSS properties to support service group names being displayed properly. So that the long sentence(words) can be broken down based on the parent `div`.
Resolves #374
=> [GT-193] Update css properties for service group

htdocs/web_portal/controllers/downtime/add_downtime.php, htdocs/web_portal/controllers/downtime/view_endpoint_tree.php, htdocs/web_portal/views/downtime/add_downtime.php, htdocs/web_portal/views/downtime/view_nested_endpoints_list.php
Clean version for #439 .
Case 1: If the user goes to the sites and tries to add recent downtimes. Then the user should be able to see the site, the services, and the endpoints pre-selected. [Pre-Selection enabled]
Case 2: If the user goes to the services and tries to add recent downtimes. Then the user should see the specific service-related endpoints that are pre-selected. [Pre-Selection enabled]
case 3: If the user goes to "Add Downtime" from the left hand menu, no Site should be pre-selected and they should be able to select any Site they have a role over (all Sites for GOCDB admins). [Pre-Selection NOT enabled]
"Resolves #229"
=> [GT-141] Add support for pre selecting endpoints

lib/Doctrine/deploy/AddCertificationStatuses.php, lib/Doctrine/deploy/AddCountries.php, lib/Doctrine/deploy/AddDowntimes.php, lib/Doctrine/deploy/AddInfrastructures.php, lib/Doctrine/deploy/AddNGIRoles.php, lib/Doctrine/deploy/AddNGIs.php, lib/Doctrine/deploy/AddProjectRoles.php, lib/Doctrine/deploy/AddProjects.php, lib/Doctrine/deploy/AddRoleTypes.php, lib/Doctrine/deploy/AddScopes.php, lib/Doctrine/deploy/AddServiceEndpoints.php, lib/Doctrine/deploy/AddServiceGroupRoles.php, lib/Doctrine/deploy/AddServiceGroups.php, lib/Doctrine/deploy/AddServiceTypes.php, lib/Doctrine/deploy/AddSiteRoles.php, lib/Doctrine/deploy/AddSites.php, lib/Doctrine/deploy/AddUsers.php, lib/Doctrine/deploy/AddUtils.php, lib/Doctrine/deploy/DeployRequiredDataRunner.php, lib/Doctrine/deploy/DeploySampleDataRunner.php
- Add space before and after '.' concatenator
- Add space after if and foreach statements
- Splits up lines that are too long
- Improves syntax of comments
- Indentation fixes
- Adds and removes spaces in various areas
resolves #481 
Resolves GT-202
=> Fix code style issues in sample data deploy scripts

htdocs/web_portal/static_html/goc5_logo.html, lib/Authentication/AuthTokens/ShibAuthToken.php
This has included:
- switching to aai-demo.egi.eu for preproduction, on the advice of EGI Check In team
- updating the expected IdPs from `subdomain/proxy/saml2/idp/metadata.php` to `subdomain/auth/realms/egi`
- moving from using epuid to voPersonID
Related ticket: https://ggus.eu/index.php?mode=ticket_info&ticket_id=164026
Once this is confirmed to work in production, before merging I'll bump the version number up to 5.10.5. This PR deliberately merges into master so that it can be released quckly, in isolation.
=>  Update ShibToken for Keycloak based EGI Check-in to master

htdocs/web_portal/GOCDB_monitor/check.php
Resolves #406
Adds http response code to check.php to allow the status of GOCDB to be checked without needing authentication.
=> Add http response code to check.php

htdocs/web_portal/static_html/goc5_logo.html
A very small release, containing only https://github.com/GOCDB/gocdb/pull/504, which was merged into `dev` during the release process for 5.11.0.
This small release ensures the 5.12.0 will only contain PHP 7.4 / Rocky 8 related changes.
=> Release 5.11.1 to dev

.github/workflows/continuous-integration.yml, composer-5.4.json, composer-5.4.lock, composer.json, composer.lock
This PR soft drops support for PHP 5.X, in favour of PHP 7.4 support "out of the box".
It is still possible to run GOCDB on PHP 5.X - however this will require specific deployments reverting this commit to restore the appropriate composer files. 
The `composer-5.4.{json, lock}` files will remain in the short term to facilitiate the above and to enable continued testing of the codebase against PHP 5.X. These files will be removed from the repository after 1st July 2024, along with automated testing of PHP 5.X.
NB: The diff rendered here is slightly weird...
- it appears as a rename of the composer-7.4 files to the composer-5.4 files, which is not what has happened.
- the pre-existing composer files were renamed to composer-5.4 files and then the composer-7.4 files were renamed to the …
=> Soft drop PHP 5.X support, in favour of PHP 7.4 "out of the box"

.github/workflows/continuous-integration.yml
- MariaDB 10.11 is readily install-able on Rocky8 and is the version we run in production.
- MariaDB 10.11 would appear to be the last version in the 10.X series.
- MariaDB 11.4 is the first version in the 11.X series with long term support, so test against it.
- Also test against the newest image in the 11.X series.
- Also test against the "latest" docker image available. In the near term, this is likely to the same image as "11". However testing against "latest" will mean we test against 12 automatically when it is released.
- Use `mariadb-admin` as admin command.
- MariaDB <10.3 required mysqladmin be used.
- MariaDB 10.4 to <11.0 allow both mysqladmin and mariadb-admin to be used.
- MariaDB 11+ requires mariadb-admin.
=> Unit test against newer versions of MariaDB

composer.json, composer.lock
ORM 2.9 seems to be as high as we can go now without starting to hit errors that at first glance seem to be because of our version of PHPUnit.
> Exception: Serialization of 'Closure' is not allowed
NB: A workable set of packages under ORM 2.10 and 2.11 was once achievable with our version of PHPUnit in https://github.com/GOCDB/gocdb/pull/455, but I guess the ecosystem has move on since then - using the commits in https://github.com/GOCDB/gocdb/pull/455 would result in some packages being downgraded from the current state of dev.
=> Update to ORM 2.9

htdocs/web_portal/static_html/goc5_logo.html, lib/Authentication/AuthTokens/ShibAuthToken.php
- Co-authored-by: gregcorbett <gregcorbett@users.noreply.github.com>
Resolves https://github.com/GOCDB/gocdb/issues/498
[GT-469](https://stfc.atlassian.net/browse/GT-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
If a user authenticates with EGI CheckIn, but does not have the correct permission to view gocdb, they are given a basic error message.
This error message references an older entitlement / the EGI wiki. This should be updated to the newer entitlement and update the references.
[GT-469]: https://stfc.atlassian.net/browse/GT-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update code to reflect the new EGI checkin error message(Master)

lib/Authentication/AuthTokens/X509AuthenticationToken.php
PHP 7.4 (sensibly) raises a notice when trying to access `false` as if it where an array, i.e. via `$Plain_Client_Cerfificate['name']`
Accessing `false` as if it were an array is not enough to break anything currently - but the notice does get raised every time someone access GOCDB via, for example, EGI CheckIn.
This PR address that issue and eliminates the notice.
=> Improve handling when no certificate is provided.

lib/Authentication/AuthTokens/X509AuthenticationToken.php
- $Plain_Client_Cerfificate is an array when a certificate has been provided, and a boolean (false) when no certificate is provided.
- As such, if _and only if_ $Plain_Client_Cerfificate _is not_ an array do we want to return here.
=> Fix handling of missing X509 certificate

htdocs/web_portal/GOCDB_monitor/tests.php, htdocs/web_portal/static_html/goc5_logo.html
Resolves GT-759
Reworked branch into a hotfix as discussed in GT-759 and #535, as such it deliberately merges into `master`.
Following updates to database infrastructure, new failure modes have presented themselves - i.e. the database is healthy enough to pass the basic connection check - but not healthy enough to be used beyond that.
This is a heavier weight (but by no means a heavy weight) check that actually tries to use the database and may be more useful here.
It is certainly no worse, i.e. if the database is down - this new check still fails.
=> Enhance check on database used on monitoring page (master)
